/* eslint-disable prefer-const */
/* eslint-disable no-prototype-builtins */
import { type ClassValue, clsx } from "clsx";
import qs from "qs";
import { twMerge } from "tailwind-merge";

import { aspectRatioOptions } from "@/constants";
/**
 * The function `cn` in TypeScript merges multiple class values using `clsx` and `twMerge`.
 * @param {ClassValue[]} inputs - The `inputs` parameter in the `cn` function is a rest parameter that
 * allows you to pass any number of arguments of type `ClassValue`. These arguments can be strings,
 * arrays of strings, or objects where the keys are class names and the values are boolean expressions
 * to conditionally apply the class
 * @returns The `cn` function is returning the result of merging the class names passed as arguments
 * using the `clsx` function and then applying Tailwind CSS utility classes using the `twMerge`
 * function.
 */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// ERROR HANDLER
/**
 * The `handleError` function in TypeScript checks the type of error and logs appropriate messages
 * before throwing an error.
 * @param {unknown} error - The `handleError` function takes an `error` parameter of type `unknown`,
 * which means it can be any type of value. The function then checks the type of the `error` parameter
 * and handles it accordingly:
 */
export const handleError = (error: unknown) => {
  if (error instanceof Error) {
    // This is a native JavaScript error (e.g., TypeError, RangeError)
    console.error(error.message);
    throw new Error(`Error: ${error.message}`);
  } else if (typeof error === "string") {
    // This is a string error message
    console.error(error);
    throw new Error(`Error: ${error}`);
  } else {
    // This is an unknown type of error
    console.error(error);
    throw new Error(`Unknown error: ${JSON.stringify(error)}`);
  }
};

// PLACEHOLDER LOADER - while image is transforming
/**
 * The function `shimmer` generates an SVG element with a shimmer effect using linear gradient
 * animation.
 * @param {number} w - The parameter `w` represents the width of the SVG element in the `shimmer`
 * function. It determines how wide the SVG element will be rendered on the screen.
 * @param {number} h - The `h` parameter in the `shimmer` function represents the height of the SVG
 * element that will be generated by the function. This height will be used to set the height of the
 * SVG element as well as the height of the rectangles inside the SVG.
 */
const shimmer = (w: number, h: number) => `
<svg width="${w}" height="${h}" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <linearGradient id="g">
      <stop stop-color="#7986AC" offset="20%" />
      <stop stop-color="#68769e" offset="50%" />
      <stop stop-color="#7986AC" offset="70%" />
    </linearGradient>
  </defs>
  <rect width="${w}" height="${h}" fill="#7986AC" />
  <rect id="r" width="${w}" height="${h}" fill="url(#g)" />
  <animate xlink:href="#r" attributeName="x" from="-${w}" to="${w}" dur="1s" repeatCount="indefinite"  />
</svg>`;

/**
 * The function `toBase64` converts a string to base64 encoding, and the `dataUrl` constant generates a
 * data URL for an SVG image encoded in base64.
 * @param {string} str - The `str` parameter in the `toBase64` function is a string that will be
 * converted to a base64 encoded string. In the provided code snippet, the `shimmer(1000, 1000)`
 * function is used to generate an SVG image, which is then converted to a
 */
const toBase64 = (str: string) =>
  typeof window === "undefined"
    ? Buffer.from(str).toString("base64")
    : window.btoa(str);

export const dataUrl = `data:image/svg+xml;base64,${toBase64(
  shimmer(1000, 1000)
)}`;
// ==== End

// FORM URL QUERY
/**
 * The `formUrlQuery` function takes search parameters, a key, and a value, and returns a URL with the
 * updated query parameters.
 * @param {FormUrlQueryParams}  - The `formUrlQuery` function takes in an object with the following
 * properties:
 * @returns The function `formUrlQuery` is returning a URL with updated query parameters based on the
 * provided `key` and `value`. The updated URL includes the new query parameter specified by the `key`
 * and `value` parameters, while maintaining the existing query parameters from the `searchParams`. The
 * returned URL is constructed using `window.location.pathname` and the updated query parameters are
 * serialized using `qs.stringify
 */
export const formUrlQuery = ({
  searchParams,
  key,
  value,
}: FormUrlQueryParams) => {
  const params = { ...qs.parse(searchParams.toString()), [key]: value };

  return `${window.location.pathname}?${qs.stringify(params, {
    skipNulls: true,
  })}`;
};

// REMOVE KEY FROM QUERY
/**
 * The function removes specified keys from a URL query string and filters out null or undefined
 * values.
 * @param {RemoveUrlQueryParams}  - The `removeKeysFromQuery` function takes in an object with two
 * properties:
 */
export function removeKeysFromQuery({
  searchParams,
  keysToRemove,
}: RemoveUrlQueryParams) {
  const currentUrl = qs.parse(searchParams);

  keysToRemove.forEach((key) => {
    delete currentUrl[key];
  });

  // Remove null or undefined values
  Object.keys(currentUrl).forEach(
    (key) => currentUrl[key] == null && delete currentUrl[key]
  );

  return `${window.location.pathname}?${qs.stringify(currentUrl)}`;
}

// DEBOUNCE
/**
 * The `debounce` function in TypeScript delays the execution of a function until a specified time has
 * passed without additional calls.
 * @param func - The `func` parameter is a function that takes any number of arguments and does not
 * return any value (void).
 * @param {number} delay - The `delay` parameter in the `debounce` function represents the amount of
 * time in milliseconds to wait before invoking the `func` function after the last call to the
 * debounced function.
 * @returns A debounced function is being returned.
 */
export const debounce = (func: (...args: any[]) => void, delay: number) => {
  let timeoutId: NodeJS.Timeout | null;
  return (...args: any[]) => {
    if (timeoutId) clearTimeout(timeoutId);
    timeoutId = setTimeout(() => func.apply(null, args), delay);
  };
};

// GE IMAGE SIZE
export type AspectRatioKey = keyof typeof aspectRatioOptions;
export const getImageSize = (
  type: string,
  image: any,
  dimension: "width" | "height"
): number => {
  if (type === "fill") {
    return (
      aspectRatioOptions[image.aspectRatio as AspectRatioKey]?.[dimension] ||
      1000
    );
  }
  return image?.[dimension] || 1000;
};

// DOWNLOAD IMAGE
/**
 * The `download` function in TypeScript downloads a resource from a given URL and saves it with a
 * specified filename, handling errors appropriately.
 * @param {string} url - The `url` parameter is a string that represents the URL of the resource you
 * want to download.
 * @param {string} filename - The `filename` parameter is a string that represents the name under which
 * the downloaded file will be saved on the user's device.
 */
export const download = (url: string, filename: string) => {
  if (!url) {
    throw new Error("Resource URL not provided! You need to provide one");
  }

  fetch(url)
    .then((response) => response.blob())
    .then((blob) => {
      const blobURL = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = blobURL;

      if (filename && filename.length)
        a.download = `${filename.replace(" ", "_")}.png`;
      document.body.appendChild(a);
      a.click();
    })
    .catch((error) => console.log({ error }));
};

// DEEP MERGE OBJECTS
/**
 * The function `deepMergeObjects` recursively merges two objects deeply, prioritizing values from the
 * second object when conflicts arise.
 * @param {any} obj1 - obj1 is the first object to be merged.
 * @param {any} obj2 - obj2 is an object that will be merged into obj1.
 * @returns The `deepMergeObjects` function returns a new object that is a deep merge of `obj1` and
 * `obj2`.
 */
export const deepMergeObjects = (obj1: any, obj2: any) => {
  if (obj2 === null || obj2 === undefined) {
    return obj1;
  }

  let output = { ...obj2 };

  for (let key in obj1) {
    if (obj1.hasOwnProperty(key)) {
      if (
        obj1[key] &&
        typeof obj1[key] === "object" &&
        obj2[key] &&
        typeof obj2[key] === "object"
      ) {
        output[key] = deepMergeObjects(obj1[key], obj2[key]);
      } else {
        output[key] = obj1[key];
      }
    }
  }

  return output;
};
